[[ssamb]]
== Asynchronous Memory Buffer ISA Extension (Ssamb)

An asynchronous memory buffer (AMB) serves as a sink for trace or similar asynchronous data, generated by hardware in parallel with software execution.  Multiple such buffers may be implemented by a hart, depending on the number of separate sources of asynchronous data generation implemented.

The buffer is contiguous in the virtual address space, but may be distributed in the physical (or guest physical) address space.  It is a circular buffer by default, such that writes commence at the base, and overwrite any older data there once the buffer is full and the write pointer wraps.  There exists a mechanism to pend a local interrupt before the buffer wraps, or to stop accepting data once the buffer is full, for cases where software does not wish to have any asynchronous data overwritten.

Ssamb is never implemented as a stand-alone extension. Each instance of Ssamb is implemented alongside one or more extensions that include a source of asynchronous data, such as Sspdis or Smstrc*/Ssstrc*.  For each instance of Ssamb the `samb*` registers below will be implemented, with names and CSR numbers specific to the feature or extension that employs Ssamb.

[WARNING]
====
_There is still an open question whether AMB should simply require pinned pages, and throw an error if a translation fault occurs.  For self-hosted trace buffers, other architectures either require pinning pages, or allow only guest-page faults.  Pinning requires that the entire buffer be kept resident, which adds to memory pressure, and limits the size of the buffer. But it avoids some hardware complexity and page fault overheads.  If pinning is not required, then pre-translation likely needs to be required, so that trace flush does not require a translation fault or guest-page fault._

_One challenge of requiring pinned pages is that there is no easy way for a hypervisor to know which pages a guest has allocated to AMB.  A hypervisor would likely need to emulate the AMB interface, or require a hypercall (and hence an enlightened guest) to configure it, while relying on the guest not to remap the AMB pages in the VS-stage page tables.  This complexity could be avoided if at least guest-page faults are allowed._

_If pages are not pinned and asynchronous data is infrequently written (consider PDIS with a low sample rate), there is a chance that the buffer page may be swapped out between writes.  For such cases the kernel may choose to pin the page(s) even if pinning is not required._

_There are also middle-ground options.  Some extensions that leverage Ssamb may require pinning while others don't.  For instance, perhaps trace requires pinning but PDIS does not.  Or we could leave demand paging support optional/discoverable, which would mean software would have to support both approaches.  More discussion is needed here.  The current plan is to wait until the POC to evaluate options.  In the meantime, the Ssamb ISA includes support for demand paging._
====

=== CSRs

[[sambcs]]
==== Supervisor Asynchronous Memory Buffer Configuration and Status Register (`sambcs`)

The `sambcs` register is a 64-bit read-write register that provides configuration and status fields for the asynchronous memory buffer.  

Optionally, if RV32 is supported, bits 63:32 of `sambcs` can be accessed via the `sambcsh` CSR.

.Supervisor Asynchronous Memory Buffer Configuration and Status Register (`sambcs`)
[wavedrom, , svg]
....
{reg: [
    {bits: 1, name: 'EN'},
    {bits: 1, name: 'TF'},
    {bits: 1, name: 'BMI'},
    {bits: 4, name: 'WPRI', type: 1},
    {bits: 5, name: 'SIZE'},
    {bits: 20, name: 'TFPTR'},
    {bits: 2, name: 'BMITH'},
    {bits: 1, name: 'BMIEN'},
    {bits: 1, name: 'SOF'},
    {bits: 25, name: 'WPRI', type: 1},
    {bits: 1, name: 'WRAP'},
    {bits: 1, name: 'EMPTY'},
    {bits: 1, name: 'TRV'},
], config:{lanes: 4, hspace:1024}}
....

When EN=1, the AMB is enabled to receive asynchronous data from source(s).  Once enabled, the AMB may translate buffer page(s), which can result in translation faults and/or guest-page faults, and cache those translations.  See <<ambaddr>> for address translation details, and see <<ambendis>> for details on enabling and disabling AMB.

The TF and BMI bits report the cause of a pended local asynchronous memory buffer interrupt (LAMBI).  When BMI=1, a buffer management interrupt was pended.  When TF=1, a buffer translation fault occurred.  See <<ambaddr>> for address translation details.  Hardware sets these fields when the LAMBI is pended.  Software should clear TF and BMI once the associated LAMBI has been serviced.  See <<lambi-handling>> for more on servicing LAMBIs.

When a buffer translation fault occurs, the buffer offset associated with the offending page is written to TFPTR, such that the full virtual address of the page base can be derived by combining the base address portion of `sambaddr` with the offset value as shown below.

FaultAddress = (`sambaddr` & (2^`sambcs`.SIZE+12^ - 1)) | (`sambcs`.TFPTR<<12)

NOTE: _Because implementations may pre-translate AMB pages (see <<ambaddr>>), translation faults can occur both for the current page (indicated by the address in `sambaddr`) and for following pages that have not yet been written.  Thus the address in `sambaddr` may not reflect the page that incurred the AMB translation fault.  TFPTR provides the means to report a fault to a different page within the AMB._

The buffer size is 2^SIZE+12^, supporting sizes from 4 KB (SIZE=0) to 4 GB (SIZE=20).  SIZE is a WARL field with values 21..31 reserved.  An AMB instance may implement only a subset of supported SIZE values.  The maximum implemented size can be discovered by writing all 1s to SIZE and reading back the resulting value.  All sizes between the minimum (4 KB) and the maximum implemented size are implemented.

WARNING: _The largest AUX buffer size allowed by Linux perf for self-hosted trace from other architectures is 4 MiB, but those require pinned memory._

The BMIEN bit enables buffer management interrupts.  When BMIEN=1, a LAMBI is pended when a hardware increment of `sambaddr` causes the two most significant bits of the write pointer offset portion to transition to match BMITH.  For example, if BMIEN=1 and BMITH=2, a LAMBI will be pended when the buffer is half full.

The EMPTY bit is a read-only indication to software that all internally buffered asynchronous data has been flushed and is visible to software reads.

NOTE: _EMPTY should factor in any empty indication from the associated data source(s), such that EMPTY is set only when all enabled data sources are empty._

The WRAP bit indicates that the buffer has wrapped at least once, and hence the data above the write pointer is valid.  If SOF (Stop-on-full) is set, any asynchronous data received after the buffer fills (WRAP=1) is dropped.  In this case (SOF=1 and WRAP=1), `sambaddr` will hold the address of the base of the buffer.

The TRV bit is a read-only indication to software that the hardware has successfully translated the buffer current page, and optionally one or more following pages.  See <<ambendis>> for more details. 

Software should only write to `sambcs` while any associated asynchronous data sources are disabled and `sambcs`.EMPTY=1, to avoid race conditions with hardware updates while AMB writes are in flight.  AMB behavior is UNSPECIFIED otherwise.

Similarly, status bits (TF, BMI, WRAP, EMPTY, TRV) should be considered volatile while asynchronous data is incoming.  To stabilize the values of status bits, follow the same guidance above to ensure that asychronous data is no longer incoming.

==== Supervisor Asynchronous Memory Buffer Address Register (`sambaddr`)

The `sambaddr` register is an SXLEN-wide WARL register that holds the virtual address to which the next byte of asynchronous data will be written.  Upon each hardware write to the AMB, the address is incremented by the number of bytes written.

The address actually comprises the buffer base and the write pointer offset.  Because the buffer base is aligned to its size, the write pointer offset is `sambaddr`[(11 + `sambcs`.SIZE):0].  When hardware writes the last byte of the buffer, the write pointer offset portion wraps to 0.

Some instantiations of AMB may support only buffer writes that are aligned to a fixed size.  In such cases the least significant bits of `sambaddr`, those that offset into the aligned range, may be hardcoded to 0.

`sambaddr` need not be capable of holding an invalid address.

Software should only write to `sambaddr` while AMB is disabled and empty (`sambcs`.EN=0 and `sambcs`.EMPTY=1).  AMB write behavior is UNSPECIFIED otherwise.

==== Interrupt Registers

WARNING: _This section gets integrated into 3.1.9 and others_

The local asynchronous memory buffer interrupt (LAMBI) bit in `mip`, `mie`, and `mideleg` is writable.  For implementations that support S-mode, the LAMBI bit in `sip` and `sie` is writable.  For implementations that support the H extension, the LAMBI bit in `vsip` and `vsie` is writable, and, when `mideleg`.LAMBI=1, the LAMBI bit in `hideleg` is writable.

For implementations that support Smaia, the LAMBI bit in `mvip` and `mvien` is writable.  For implementations that support Smaia/Ssaia and the H extension, the LAMBI bit in `hvip` and `hvien` is writable.

LAMBI is bit 14 in all registers reference above.  The priority of LAMBIs lies immediately below that of local counter overflow interrupts (LCOFIs).

[[ambendis]]
=== Enabling and Disabling

When enabling asynchronous data collection, software should first initialize `sambaddr`, then configure and enable AMB by writing `sambcs`.  For RV32, `sambcsh` should be initialized before AMB is enabled in `sambcs`.

Once AMB is enabled (`sambcs`.EN=1), translation of the current AMB page (at `sambaddr`), and optionally one or more following page(s), will commence.  Software should wait until `sambcs`.TRV=1 before enabling enabling the asynchronous data source(s), to avoid loss of data while waiting for this translation process.  One or more translation faults and/or guest-page faults may have to be serviced before TRV=1.

When disabling asynchronous data collection, software should first disable asynchronous data source(s), which will initiate a flush of any internally buffered data.  Software should then wait until AMB reports empty (`sambcs`.EMTPY=1), to ensure that data downstream from the source is not dropped.  After this AMB can be disabled by clearing `sambcs`.EN.

Failure to follow the guidance above when enabling or disabling asynchronous data generation to AMB may result in loss of asynchronous data.

=== Memory Semantics

Like other stores, the ordering and cache semantics of hardware AMB writes are dictated by PMAs and/or page-based memory types (Svpbmt).  However, hardware writes of asynchronous data are not ordered with respect to explicit memory operations, including FENCE instructions.  Further, AMB writes are not ordered with respect to other AMB writes, or other implicit writes.  To effect an asynchronous data fence software should follow the AMB disable steps described in <<ambendis>>. 

[NOTE]
====
_For asynchronous data sources that are processed offline (e.g., instruction trace), it is likely desirable to assign buffer pages a non-cacheable but weakly ordered attribute (e.g., PBMT=NC).  This avoids having trace data that won't be read soon displace workload working set data from the caches._

_For asynchronous data sources that are processed online (e.g., sample records, such that each record is collected as it is written), it may be desirable to assign buffer pages a cacheable attribute.  This avoids adding cache-miss latency to online collection routines._
====

[[ambaddr]]
=== Asynchronous Write Privilege and Address Translation

The effective privilege mode of AMB writes is selected by bits associated with each AMB instance in `menvcfg` and, if the H extension is implemented, `henvcfg`.  For the AMB associated with self-hosted trace (STRC), the full set of configuration options is illustrated below.

[options="header", width="70%"]
|===
| `menvcfg`.STRCS | `henvcfg`.STRCV | Effective Privilege Mode | Translation
| 0 | - | M-mode | None (Bare)
| 1 | 0 | S/HS-mode | `satp`
| 1 | 1 | VS-mode | `vsatp`/`hgatp`
|===

NOTE: _Using a fixed effective privilege mode for asynchronous data writes, rather than using the current privilege mode, allows supporting system-wide uses, where recording persists across privilege modes._

WARNING: _This does not cleanly support a nested hypervisor tracing/monitoring a true guest.  In such a usage, the guest trace would ideally use the nested hypervisor's `vsatp`/`hgatp` to translate AMB addresses.  In the TG we discussed adding `tatp` and `hgtatp` registers that are used just for translation of AMB addresses, and could be assigned the values of the nested hypervisor's `vsatp`/`hgatp` in this usage.  But this feels like overkill to support this usage.  A root hypervisor can support this usage using its own `satp` to translate AMB addresses during guest execution, then map those physical AMB pages to the nested hypervisor's AMB range via `hgatp`._

The process of translating AMB write addresses can result in translation faults.  A page fault incurred during first-stage translation, controlled by `satp` when the effective privilege mode is S-mode or `vsatp` when the effective privilege mode is VS-mode, pends a LAMBI interrupt with a cause of translation fault (`sambcs`.TF=1), and with the buffer offset of the offending page indicated in `sambcs`.TFPTR.

NOTE: _Unlike explicit stores or other implicit stores, asynchronous memory buffer writes do not raise "Store/AMO Page Fault" exceptions as a result of translation faults.  By instead pending a LAMBI with TF=1, risks of destructive nested page faults, e.g., as a result of a synchronous page fault followed by an asynchronous page fault, are avoided.  Further, unlike page fault exceptions, a LAMBI pended for an AMB translation fault can remain pending if it cannot be taken in the current privilege mode._

A page fault incurred during the second stage, or G-stage, translation raises a Load or Store/AMO guest-page fault, just as explicit accesses and other implicit accesses do.

NOTE: _AMB guest-page faults do not raise LAMBIs since the two must be handled in different privilege modes, much the way non-AMB page fault exceptions and guest-page fault exceptionss are._

WARNING: _Adding yet another new local interrupt for AMB guest-page faults was considered.  It would avoid the need to hold guest-page faults pending to avoid nesting issues (see <<ambpretrans>>), but this was ultimately deemed insufficient motivation to consume another local priv-ISA interrupt encoding._

[[ambtlb]]
==== Caching AMB Address Translations

Implementations should cache AMB address translations in order to improve performance and avoid asynchronous data loss.  Cached AMB page translations can be flushed by SFENCE and HFENCE instructions, globally or per ASID/VMID, just as other translations are.  See <<sfence.vma>> and <<hfence.vma>>.  

NOTE: _Depending on the AMB size and the asynchronous data rate, AMB writes can touch many pages in a short amount of time.  However, AMB uses page translations efficiently, writing exclusively to a single page until it is full, then moving to the next and writing exclusively to it.  Rather than allowing AMB writes to displace explicit memory access translations from the primary TLB, it may be more efficient to store cached AMB translations in a very small dedicated AMB TLB.  Two entries (current page and next page) will be sufficient for most implementations, though more may be warranted if the implementation pre-translates more than one page ahead._

To avoid asynchronous data loss, software must disable AMB (as prescribed in <<ambendis>>) before invalidating an active AMB TLB entry.  Active AMB TLB entries include the current AMB page (that is, the page that holds the address in `sambaddr`) and the pre-translated page(s) immediately following, which may be written in the event the data source is disabled and flushed.  An AMB page can only be pre-translated and translation-cached if it is present and writable by the AMB's effective privilege mode.

If the current AMB page is invalidated, AMB will backpressure the source until the entry is restored.  If internal buffers fill in the interim, the source may have to drop data.  Further, if any pre-translated and active AMB TLB entries are invalidated, internally buffered data may not be able to be flushed without a trap, which risks unrecoverable data loss.  See <<ambpretrans>> for details.

Any AMB and corresponding data source that software disabled in order to invalidate a TLB entry can be re-enabled afterward, using the guidance in <<ambendis>>.

[[ambpretrans]]
==== AMB Page Pre-translation

Any loss of asynchronous data is undesirable, but it is at times unavoidable.  Asynchronous data loss falls into two categories:

** *Recoverable data loss*, which occurs when data is dropped by the data source.  The source can ensure that data is dropped on record (or packet/message) boundaries, and that software is provided with any information needed to process the data despite the loss.
** *Unrecoverable data loss*, which occurs when data is dropped downstream from the source.  In this case data loss may not be aligned with data record boundaries, and hence partial records may be observed.  Software is typically not able to process impacted records and, depending on the encoding scheme, may not be able to process any data following the loss.

Implementations should endeavor to minimize recoverable data loss, while unrecoverable data loss must be avoided entirely for software that follows the guidance provided in this specification.  To accomplish the latter, implementations must follow the guidelines below.

. While AMB is enabled (`sambcs`.EN=1), utilize AMB page pre-translation to ensure that all data residing in internal buffers can be flushed without requiring a trap (translation fault or guest-page fault).
** Pre-translation involves retrieving and caching address translations for not only the current AMB page (that is, the page that holds the AMB write pointer in `sambaddr`), but one or more subsequent AMB pages.  A simple implementation would cache translations for the current and next AMB page.  When page X is filled, writes transition to (already translated) page X+1, and translation begins for page X+2.  The number of pages to pre-translate should be one more than is needed to flush all internally buffered data.
** Flushes may be initiated in contexts where a trap cannot be properly handled; consider a translation fault raised while a hypervisor is saving guest AMB state during guest context switch.  In such cases, if AMB is disabled before internal buffers are fully flushed (i.e., `sambcs`.EN cleared while `sambcs`.EMPTY=0), data residing in internal buffers may be dropped in an unrecoverable manner.  Pre-translation avoids this by ensuring that a trap during flush is never necessary.
** Pre-translation must be suspended when it encounters a translation fault or guest-page fault condition.  This ensures that a translation fault is not overwritten by a translation fault for a programmatically younger page.  When suspended, pre-translation should resume when either `sambcs`.TF is cleared (translation fault serviced) or when the HFENCE.GVMA instruction completes (part of the guest-page fault handler flow).

. Backpressure to the data source before the available space in translated AMB pages is less than the size of internal buffering.
** Consider an implementation with 256 bytes of internal storage, and that pre-translates 1 page ahead.  If that pre-translation is delayed and `sambaddr` increments to within 256 bytes of the current page boundary, there is risk that a flush will require a trap.  By preemptively backpressuring to the source before this occurs, it is guaranteed that any data loss that could result is recoverable.

. A guest-page fault condition encountered during pre-translation must be held pending while V=0.
** This ensures that the exception is not taken when it could be destructive (e.g., when already executing a guest-page fault handler).
** If AMB is disabled while such a guest-page fault is pending, the pending fault can be dropped.  The condition will be re-discovered if/when AMB is re-enabled with the same configuration.
** If AMB writes are configured with VS-mode privilege, it is expected that the data source will be configured to inhibit asynchronous data generation when V=0.  However, buffered data may still be emitted while V=0.  The guidelines above ensure that no trap is required to complete a buffer flush, hence deferring the guest-page fault in such cases does not risk data loss.

[[lambi-handling]]
[appendix]
=== Handling Local Asynchronous Memory Buffer Interrupts

Local asynchronous memory buffer interrupts (LAMBIs) are raised as a result of either of the two conditions below.

a. The buffer management mechanism is enabled (`sambcs`.BMIEN=1) and the buffer threshold has been reached (see `sambcs`.BMITH definition in <<sambcs>>).  In this case `sambcs`.BMI is set to 1.
b. A translation fault was encountered while translating an AMB page.  In this case `sambcs`.TF is set to 1.

Software should follow the sequence below when servicing a LAMBI in privilege mode _x_.

For each `sambcs` register implemented:

1. Disable the asynchronous data source following the guidance in <<ambendis>>.
** This ensures that asychronous data generation ceases, and that all data generated has been emitted to the AMB.  This serves to avoid race conditions where conditions (a) and/or (b) above occur during LAMBI handler execution, which could result in the LAMBI being cleared without all causes being serviced.
2. Clear `__x__ip`.LAMBI
** Doing this after step 1 ensures that any LAMBI conditions that arise during step 1 do not result in a spurious LAMBI following this one.
** This step must be done before step 4, but could optionally follow step 3.
3. Service the LAMBI cause(s).
** If `sambcs`.TF=1, call the appropriate routine to service the translation fault, then clear TF.  This routine may be shared with the page fault exception handler.
** If `sambcs`.BMI=1, perform any buffer management tasks desired, including any modifications to the AMB configuration.  Then clear BMI.
4. Re-enable any data sources disabled in step 1, following the guidance in <<ambendis>>.
** After this step asynchronous data generation resumes, which could result in a new LAMBI being pended.  Because `__x__status`.__x__IE=0 during handler execution, any new LAMBI will remain pending until the handler completes.
** The handler could opt to perform step 4 for each AMB instance after steps 1-3 are completed for all instances, if data generation during handler execution is not desired.

